#ifndef AUTOCAR_AUTONOMOUS_CONFIG_H
#define AUTOCAR_AUTONOMOUS_CONFIG_H

/* 自动驾驶源代码调参入口。速度mm/s、时间ms、PWM千分比，均为低速初值。 */
#define AUTO_START_KEY_PIN C15
#define AUTO_STOP_KEY_PIN C14
#define AUTO_CANCEL_KEY_PIN C12
#define AUTO_KEY_DEBOUNCE_MS 30U
#define AUTO_TICK_MS 10U
/* 用户确认M1左/M2右；编码器正号尚未实测，前进为负时将对应值改为-1。 */
#define AUTO_MOTOR1_IS_LEFT 1
#define AUTO_LEFT_ENCODER_SIGN 1
#define AUTO_RIGHT_ENCODER_SIGN 1
#define AUTO_CRUISE_SPEED_MM_S 180.0f
#define AUTO_CURVE_SPEED_MM_S 120.0f
#define AUTO_ELEMENT_SPEED_MM_S 100.0f
#define AUTO_FINISH_SPEED_MM_S 100.0f
#define AUTO_ACCEL_MM_S2 200.0f
/* 转弯时外轮目标稍快、内轮稍慢；0关闭，0.15为待标定的最大15%差速比例。 */
#define AUTO_TURN_DIFFERENTIAL_RATIO 0.15f
#define AUTO_MAX_DUTY_PERMILLE 100U
#define AUTO_DUTY_STEP_PER_TICK 3U
#define AUTO_SPEED_KP 0.18f
#define AUTO_SPEED_KI 0.15f
#define AUTO_SPEED_KD 0.0f
#define AUTO_SPEED_INTEGRAL_LIMIT 45.0f
#define AUTO_SPEED_FEEDFORWARD 0.30f
#define AUTO_SPEED_FILTER_ALPHA 0.30f
#define AUTO_SPEED_DERIVATIVE_TAU_S 0.04f
/* 像素误差右正；舵机命令左正，负号在控制器内统一变换。 */
#define AUTO_STEERING_KP 18.0f
#define AUTO_STEERING_KI 0.0f
#define AUTO_STEERING_KD 0.5f
#define AUTO_STEERING_DERIVATIVE_TAU_S 0.06f
#define AUTO_STEERING_NEAR_WEIGHT 0.65f
#define AUTO_STEERING_FAR_WEIGHT 0.35f
#define AUTO_STEERING_LIMIT_PERMILLE 1000.0f
/* 沿用1480us中位及1420..1540us机械窗口，自动循迹斜率单独可调。 */
#define AUTO_SERVO_STEP_US 6U
#define AUTO_SERVO_INTERVAL_MS 20U
#define AUTO_CENTER_SETTLE_MS 500U
#define AUTO_FRAME_MAX_AGE_MS 150U
#define AUTO_SERVO_MAX_AGE_MS 100U
#define AUTO_FEEDBACK_MAX_AGE_MS 30U
#define AUTO_MIN_CONFIDENCE 45U
/* 已确认且限距的十字/环岛允许部分缺边；未确认候选不得使用此门限。 */
#define AUTO_ELEMENT_MIN_CONFIDENCE 35U
#define AUTO_START_GOOD_FRAMES 3U
#define AUTO_BAD_FRAMES_TO_STOP 3U
#define AUTO_WRONG_DIRECTION_MM_S 30
#define AUTO_WRONG_DIRECTION_MS 100U
#define AUTO_MAX_MEASURED_SPEED_MM_S 900
#define AUTO_STALL_SPEED_MM_S 10
#define AUTO_STALL_DUTY_PERMILLE 55U
#define AUTO_STALL_TIME_MS 1500U
#define AUTO_MAX_RUN_TIME_MS 180000U
/* 近场斑马线需要连续3帧；第一次为出发，离开后返回才为终点。 */
#define AUTO_ZEBRA_MIN_ROW 80U
#define AUTO_ZEBRA_CONFIRM_FRAMES 3U
#define AUTO_ZEBRA_CLEAR_FRAMES 5U
#define AUTO_ZEBRA_CLEAR_DISTANCE_MM 500U
#define AUTO_MIN_LAP_DISTANCE_MM 5000U
#define AUTO_MIN_LAP_TIME_MS 8000U
/* 从近场标记确认位置继续前进的参考距离；须实测相机视野、车长、制动余量。 */
#define AUTO_FINISH_ADVANCE_MM 500U
#define AUTO_FINISH_MAX_TIME_MS 10000U
#if AUTO_TICK_MS != 10U
#error "自动驾驶控制周期必须为10ms"
#endif
#if AUTO_MAX_DUTY_PERMILLE == 0U || AUTO_MAX_DUTY_PERMILLE > 150U
#error "自动驾驶PWM上限必须在1..150千分比内"
#endif
#if (AUTO_LEFT_ENCODER_SIGN != 1 && AUTO_LEFT_ENCODER_SIGN != -1) || (AUTO_RIGHT_ENCODER_SIGN != 1 && AUTO_RIGHT_ENCODER_SIGN != -1)
#error "编码器方向只能为正1或负1"
#endif
#if AUTO_MOTOR1_IS_LEFT != 0 && AUTO_MOTOR1_IS_LEFT != 1
#error "电机左右映射只能为0或1"
#endif
#if AUTO_FINISH_ADVANCE_MM == 0U || AUTO_FINISH_ADVANCE_MM > 900U
#error "终点参考推进距离必须在1..900mm内，并另行实测停车位置"
#endif
#endif
