#ifndef AUTOCAR_MOTOR_TEST_CONFIG_H
#define AUTOCAR_MOTOR_TEST_CONFIG_H

/* 逐飞RT1064 V3.0的P8 MOTOR DRIVER1；通道编号来自双路电机例程。
 * 模块M1为C8/C9，M2为C6/C7。用户已确认两路参考HIGH均为前进；通道与左右轮对应仍待记录。 */
#define MOTOR_CHANNEL1_PWM              PWM2_MODULE1_CHA_C8
#define MOTOR_CHANNEL1_PWM_PIN          C8
#define MOTOR_CHANNEL1_DIRECTION_PIN    C9
#define MOTOR_CHANNEL2_PWM              PWM2_MODULE0_CHA_C6
#define MOTOR_CHANNEL2_PWM_PIN          C6
#define MOTOR_CHANNEL2_DIRECTION_PIN    C7
#define MOTOR_CHANNEL1_REFERENCE_LEVEL  GPIO_HIGH
#define MOTOR_CHANNEL2_REFERENCE_LEVEL  GPIO_HIGH
#define MOTOR_TEST_PWM_FREQUENCY_HZ     (17000U)

/* 占空比单位为千分比：100为10%，硬上限150为15%；无自动反转。 */
#ifndef MOTOR_TEST_DUTY_PERMILLE
#define MOTOR_TEST_DUTY_PERMILLE         (100U)
#endif
#define MOTOR_TEST_MAX_DUTY_PERMILLE     (150U)
#ifndef MOTOR_CONTROL_TICK_MS
#define MOTOR_CONTROL_TICK_MS           (10U)
#endif

#define MOTOR_TEST_START_KEY_PIN        C12
#define MOTOR_TEST_STOP_KEY_PIN         C14
#define MOTOR_TEST_KEY_ACTIVE_LEVEL     GPIO_LOW
#define MOTOR_TEST_KEY_DEBOUNCE_MS       (30U)
#define MOTOR_TEST_CHANNEL_DURATION_MS  (2000U)
#define MOTOR_TEST_GAP_DURATION_MS      (1000U)
#define MOTOR_TEST_RESULT_HOLD_MS        (5000U)

#endif /* AUTOCAR_MOTOR_TEST_CONFIG_H */
